use std::fs::File;
use std::io::{self, Read};
use sha2::{Sha256, Digest};
use log::{error, info, warn};

/// Expected hash of the APK (SHA-256)
/// This will be generated at build time and embedded in the binary
/// DO NOT modify manually - generated by build.rs
const EXPECTED_APK_HASH: &str = "PLACEHOLDER_HASH_WILL_BE_REPLACED_BY_BUILD_SCRIPT";

/// Download URL for legitimate app
const OFFICIAL_DOWNLOAD_URL: &str = "https://sassyconsulting.com/sassytalkie/download";

/// Integrity verification error
#[derive(Debug)]
pub enum IntegrityError {
    HashMismatch { expected: String, actual: String },
    CannotReadApk(io::Error),
    InvalidHash,
}

/// Self-integrity checker
pub struct IntegrityChecker {
    apk_path: String,
}

impl IntegrityChecker {
    pub fn new() -> Self {
        // On Android, app's own APK is at:
        // /data/app/~~RANDOM~~/com.sassyconsulting.sassytalkie-RANDOM==/base.apk
        // But we can get it via /proc/self/exe or context.getPackageCodePath()
        
        Self {
            apk_path: String::new(),
        }
    }

    /// Get APK path from /proc/self/maps
    fn get_apk_path(&self) -> Result<String, io::Error> {
        // Read /proc/self/maps to find base.apk
        let maps = std::fs::read_to_string("/proc/self/maps")?;
        
        for line in maps.lines() {
            if line.contains("base.apk") || line.contains(".apk") {
                // Extract path from line like:
                // 12345000-12346000 r--p 00000000 ... /data/app/.../base.apk
                let parts: Vec<&str> = line.split_whitespace().collect();
                if let Some(path) = parts.last() {
                    if path.ends_with(".apk") {
                        return Ok(path.to_string());
                    }
                }
            }
        }
        
        Err(io::Error::new(io::ErrorKind::NotFound, "APK path not found"))
    }

    /// Calculate SHA-256 hash of APK file
    fn calculate_apk_hash(&self, path: &str) -> Result<String, io::Error> {
        let mut file = File::open(path)?;
        let mut hasher = Sha256::new();
        let mut buffer = vec![0u8; 8192]; // 8KB buffer
        
        loop {
            let n = file.read(&mut buffer)?;
            if n == 0 {
                break;
            }
            hasher.update(&buffer[..n]);
        }
        
        let hash = hasher.finalize();
        Ok(format!("{:x}", hash))
    }

    /// Verify APK integrity
    pub fn verify(&self) -> Result<(), IntegrityError> {
        info!("Starting integrity verification...");
        
        // Skip verification if hash is placeholder (development build)
        if EXPECTED_APK_HASH.contains("PLACEHOLDER") {
            warn!("Integrity check skipped - development build");
            return Ok(());
        }

        // Get APK path
        let apk_path = self.get_apk_path()
            .map_err(IntegrityError::CannotReadApk)?;
        
        info!("APK path: {}", apk_path);

        // Calculate current hash
        let actual_hash = self.calculate_apk_hash(&apk_path)
            .map_err(IntegrityError::CannotReadApk)?;
        
        info!("Calculated hash: {}", actual_hash);
        info!("Expected hash: {}", EXPECTED_APK_HASH);

        // Compare hashes
        if actual_hash.to_lowercase() != EXPECTED_APK_HASH.to_lowercase() {
            error!("INTEGRITY VIOLATION: Hash mismatch!");
            error!("Expected: {}", EXPECTED_APK_HASH);
            error!("Actual:   {}", actual_hash);
            
            return Err(IntegrityError::HashMismatch {
                expected: EXPECTED_APK_HASH.to_string(),
                actual: actual_hash,
            });
        }

        info!("✓ Integrity verification passed");
        Ok(())
    }

    /// Show tamper warning to user
    pub fn show_tamper_warning() {
        error!("╔═══════════════════════════════════════════════════╗");
        error!("║           SECURITY WARNING                        ║");
        error!("║                                                   ║");
        error!("║  This app has been modified or tampered with.    ║");
        error!("║  For your security, it will not run.             ║");
        error!("║                                                   ║");
        error!("║  Please download the official version from:      ║");
        error!("║  {}  ║", OFFICIAL_DOWNLOAD_URL);
        error!("║                                                   ║");
        error!("║  Do not trust modified versions of this app.     ║");
        error!("╚═══════════════════════════════════════════════════╝");
    }
}

/// Global flag for integrity check result
static mut INTEGRITY_CHECK_PASSED: bool = false;

/// Constructor that runs BEFORE main()
/// This is executed when the library is loaded, before any other code
#[cfg(target_os = "android")]
#[link_section = ".init_array"]
#[used]
pub static INTEGRITY_CHECK_INIT: extern "C" fn() = {
    #[cfg_attr(any(target_os = "linux", target_os = "android"), link_section = ".text.startup")]
    extern "C" fn run_integrity_check() {
        // This runs BEFORE android_main()
        // Cannot use logging yet (not initialized)
        
        let checker = IntegrityChecker::new();
        
        match checker.verify() {
            Ok(_) => {
                // Store result in global flag
                unsafe {
                    INTEGRITY_CHECK_PASSED = true;
                }
            }
            Err(e) => {
                // Integrity check failed - terminate immediately
                unsafe {
                    INTEGRITY_CHECK_PASSED = false;
                }
                
                // Cannot show UI yet, but we can write to logcat
                // Note: android_logger not initialized yet, so this might not appear
                eprintln!("INTEGRITY CHECK FAILED: {:?}", e);
                
                // Force crash with clear message
                panic!("INTEGRITY VIOLATION: App has been tampered with. Please download from official source.");
            }
        }
    }
    
    run_integrity_check
};

/// Check if integrity verification passed
/// Called from main code to double-check
pub fn integrity_check_passed() -> bool {
    unsafe { INTEGRITY_CHECK_PASSED }
}

/// Obfuscated hash storage (alternative method)
/// Split hash into chunks to make it harder to find in binary
pub struct ObfuscatedHash {
    chunks: Vec<&'static [u8]>,
}

impl ObfuscatedHash {
    pub fn new() -> Self {
        // Split expected hash into 8 chunks of 8 characters
        // This makes it harder to search for the full hash in binary
        Self {
            chunks: vec![
                // These would be actual hash chunks
                // Example for hash starting with "abc123de..."
                b"abc123de",
                b"f4567890",
                b"12345678",
                b"90abcdef",
                // ... more chunks
            ],
        }
    }

    pub fn reconstruct(&self) -> String {
        self.chunks
            .iter()
            .map(|chunk| String::from_utf8_lossy(chunk))
            .collect::<String>()
    }
}

/// Alternative: Native method to get expected hash from secure storage
/// This could retrieve the hash from Android KeyStore or other secure location
#[cfg(target_os = "android")]
pub fn get_expected_hash_secure() -> Result<String, Box<dyn std::error::Error>> {
    // TODO: Implement retrieval from Android KeyStore
    // This would require JNI call to:
    // KeyStore keyStore = KeyStore.getInstance("AndroidKeyStore");
    // SecretKey key = (SecretKey) keyStore.getKey("expected_hash", null);
    
    Ok(EXPECTED_APK_HASH.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hash_calculation() {
        // Create a temporary file with known content
        use std::io::Write;
        let mut temp_file = tempfile::NamedTempFile::new().unwrap();
        temp_file.write_all(b"test content").unwrap();
        temp_file.flush().unwrap();
        
        let checker = IntegrityChecker::new();
        let hash = checker.calculate_apk_hash(temp_file.path().to_str().unwrap()).unwrap();
        
        // SHA-256 of "test content"
        assert_eq!(hash, "6ae8a75555209fd6c44157c0aed8016e763ff435a19cf186f76863140143ff72");
    }

    #[test]
    fn test_obfuscated_hash() {
        let obfuscated = ObfuscatedHash::new();
        let reconstructed = obfuscated.reconstruct();
        
        assert!(reconstructed.len() > 0);
    }
}
